-- MySQL Script generated by MySQL Workbench
-- Mit 30 Aug 2017 15:23:51 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facturation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facturation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facturation` DEFAULT CHARACTER SET utf8 ;
USE `facturation` ;

-- -----------------------------------------------------
-- Table `facturation`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturation`.`type` (
  `id_type` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturation`.`societes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturation`.`societes` (
  `id_societes` INT NOT NULL AUTO_INCREMENT,
  `nom_societe` VARCHAR(45) NOT NULL,
  `adresse_societe` VARCHAR(45) NOT NULL,
  `tel_societe` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL,
  `tva_societe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_societes`, `type`),
  INDEX `fk_societes_1_idx` (`type` ASC),
  CONSTRAINT `societe_type`
    FOREIGN KEY (`type`)
    REFERENCES `facturation`.`type` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `facturation`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturation`.`personne` (
  `id_personne` INT NOT NULL AUTO_INCREMENT,
  `nom_personne` VARCHAR(45) NOT NULL,
  `prenom_personne` VARCHAR(45) NOT NULL,
  `tel_personne` VARCHAR(45) NULL,
  `email_personne` VARCHAR(45) NULL,
  PRIMARY KEY (`id_personne`),
  CONSTRAINT `personne_societe`
    FOREIGN KEY (`id_personne`)
    REFERENCES `facturation`.`societes` (`id_societes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `facturation`.`factures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturation`.`factures` (
  `id_factures` INT NOT NULL,
  `numero_facture` VARCHAR(45) NOT NULL,
  `date_facture` DATE NULL,
  `bc_facture` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_factures`),
  CONSTRAINT `factures_personne`
    FOREIGN KEY (`id_factures`)
    REFERENCES `facturation`.`personne` (`id_personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `factures_societe`
    FOREIGN KEY (`id_factures`)
    REFERENCES `facturation`.`societes` (`id_societes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
